forgeflux-org/interface

.github/workflows/coverage.yml, .github/workflows/linux.yml, interface/db.py, interface/git.py, libgit/Cargo.lock, libgit/Cargo.toml, libgit/src/lib.rs, libgit/src/system.rs, migrations/20211023_01_0W52q-event-subscriptions.py
Tests both `Repo` and `System`.
1. creates a repository, complete with upstream and local(local is
on fs) remotes
2. makes changes
3.  generates a patch
4. processes the patch,
5. applies patch and pushes the changes.
---
Merge after #13
=> Tests and CI setup

.github/workflows/coverage.yml, .github/workflows/linux.yml, .gitignore, Makefile, scripts/coverage.sh
Migrated coverage report generation from tarpaulin to grcov
=> CI: coverage and test workflows

interface/forges/gitea.py, interface/forges/github.py, interface/forges/notifications.py, interface/forges/payload.py
The list that was being returned expected a `Type[str]` rather than the list of strings itself.
Does it make a huge difference? I presume [not](https://stackoverflow.com/questions/42048107/what-is-the-difference-between-class-str-and-type-str).
However, this is a best practice for defining data types.
The same issues need to be resolved with GitHub as well.
That can either be done in this PR, or, in a separate PR which connects the GitHub interface to the server.
=> Notification System Fix

Makefile, interface/forges/base.py, requirements.txt, scripts/coverage.sh, scripts/lib.sh, scripts/spellcheck.sh
Runs spellchecker on all source files
=> Check for spellings errors during testing

interface/runner/events.py, interface/runner/runner.py, scripts/spellcheck.sh
- check README
- (additionally)check spellings with misspell
=> check spellings with misspell

interface/db/__init__.py, interface/db/comments.py, interface/db/interfaces.py, interface/db/issues.py, interface/db/repo.py, interface/db/users.py, migrations/20211226_01_zx3oY-forge-data.py, tests/db/test_comments.py, tests/db/test_interface.py, tests/db/test_issue.py, tests/db/test_repo.py, tests/db/test_user.py
- Load with id implementation for the following classes:
- `DBInterfaces`
- `DBIssue`
- `DBUser`
- `DBRepo`
This is done in an effort to support lazy loading of data.
- Replace `DEFAULT NULL` clauses in databases references with `NOT NULL` clauses:
Interface behavior up until now was to store a null value for data with native origins. This implicit nature could cause problems later, so `DEFAULT NULL` clauses are replaced with `NOT NULL ` clauses to enforce mandatory linking of records against the source interface
Store and retrieve comments from database
=> Notifications2

interface/auth.py, interface/db/issues.py, interface/db/repo.py, interface/db/users.py, interface/forges/gitea/admin.py, interface/forges/payload.py, migrations/20211226_01_zx3oY-forge-data.py, requirements.txt, tests/db/test_user.py
User, Repository and Issues are deemed as (Activity Pub) Actors and so RSA key pairs are automatically generated for them when their are stored
in the DB
=> Generate key pairs for User, Repository and Issue

interface/auth.py, interface/db/issues.py, interface/db/repo.py, interface/db/users.py, interface/forges/gitea/admin.py, interface/forges/payload.py, migrations/20211226_01_zx3oY-forge-data.py, requirements.txt, tests/db/test_user.py
=> DB data to actor object for User, Issue and Repository

interface/auth.py, interface/db/issues.py, interface/db/repo.py, interface/db/users.py
=> DB data to webfinger response

interface/db/repo.py, interface/error.py, interface/forges/base.py, interface/forges/gitea/gitea.py, interface/forges/payload.py, migrations/20211226_01_zx3oY-forge-data.py, tests/db/test_comments.py, tests/db/test_issue.py, tests/db/test_repo.py, tests/db/test_subscriptions.py, tests/db/test_tasks.py, tests/forges/gitea/test_gitea.py, tests/forges/test_base.py, tests/test_errors.py
=> feat: Error HTTP response utils

interface/db/__init__.py, interface/db/activity.py, interface/db/comments.py, interface/db/issues.py, interface/forges/payload.py, interface/utils.py, migrations/20220116_01_Ur7VF-activities.py, tests/db/test_activity.py, tests/db/test_comments.py, tests/db/test_issue.py, tests/test_utils.py
- utils to work with time since unix epoch
- load ID after saving DBComments
- load ID after saving DBIssues
- DBActivity to log activities on forge data
=> feat: store activity log

interface/db/issues.py, interface/db/repo.py, interface/utils.py, tests/db/test_issue.py, tests/test_utils.py
> blocked by #70(apologies, I got the order wrong but #70 is lower in the stack)
- AP utils for `DBIssue` and enhance it's actor response message
=> feat: Issue webfinger utils on DBIssue

interface/app.py, interface/error.py, interface/webfinger.py, tests/test_webfinger.py
=> feat: Webfinger endpoint

config/settings.toml, interface/forges/base.py, interface/ns.py, tests/forges/test_base.py, tests/test_auth.py, tests/test_ns.py
Time-bound, configurable LRU caching NorthStar queries
=> feat: ns lru cache

interface/app.py, interface/issue.py, tests/test_issue.py
Implements issue actor and tests
=> feat: issue actor

config/settings.toml, interface/db/activity.py, interface/db/cache.py, interface/db/comments.py, interface/db/users.py, interface/ns.py, tests/db/test_activity.py, tests/db/test_cache.py, tests/db/test_comments.py, tests/test_user.py
=> feat: lru cached total number of comments count

config/settings.toml, interface/app.py, interface/db/activity.py, interface/db/cache.py, interface/db/comments.py, interface/db/users.py, interface/ns.py, interface/well_known/__init__.py, interface/well_known/nodeinfo.py, interface/well_known/webfinger.py, tests/db/test_activity.py, tests/db/test_cache.py, tests/db/test_comments.py, tests/test_user.py, tests/well_known/test_nodeinfo.py, tests/well_known/test_webfinger.py
> blocked by #84
implement node invo v2.0
=> feat: nodeinfo v2.0

README.md, docs/HACKING.md, docs/pre-commit
For rendered page, please see: https://github.com/realaravinth/interface/blob/docs-hacking/docs/HACKING.md
=> feat: add development instructions

docs/webfinger.md
Please see [here](https://github.com/realaravinth/interface/blob/docs-webfinger/docs/webfinger.md) for rendered content
=> feat: document interface's webfinger implementation

interface/db/comments.py, interface/db/issues.py
SUMMARY
DBIssue and DBComment loaded data from database when performing
updates via self.__update() which in some cases where unnecessary as a
fetch would have been performed just before invoking __update().
This patch introduces an optical parameter to provide recently
loaded data from DB
=> feat: conditionally load data from DB when updating issues and comments
